config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "employees#index"

  get '/login', to: 'sessions#new', as: 'login'
  post '/user_signin', to: 'sessions#create', as: 'signin'

  resources :employees
  resources :bills

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :employee
  enum status: { pending: 0, approved: 1, rejected: 2 }

  before_create :set_default_status

  def set_default_status
    self.status ||= 'pending'
  end

end

app/models/department.rb
class Department < ApplicationRecord
  validates :name, uniqueness: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
  belongs_to :user, optional: true

  validates :email, uniqueness: true

  after_create :create_user

  def create_user
    User.create(name: "#{first_name} #{last_name}", email: email, password: email, role: 'employee')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, uniqueness: true

  enum role: { admin: 0, employee: 1 }

  def is_admin?
    role == 'admin'
  end

  def is_employee?
    role == 'employee'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def is_logged_in?
    current_user.present?
  end

  def fetch_login
    unless logged_in?
      redirect_to login_path, alert: "You must be logged in to access this section"
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :validate_employee, only: [:new]
  before_action :fetch_user

  def index
    @bills = Bill.all
    @approved_count = @bills.select(:id).where(status: 'approved').count
  end

  def new
    @employee = Employee.find_by(user_id: @current_user.id)
  end

  def create
    @bill = Bill.new(bill_params)

    if @bill.save
      redirect_to bills_path
    else
      flash.now[:danger] = ''
      render 'new'
    end
  end

  def update
    @bill = Bill.find_by(id: params[:id])
    @bill.update(status: params[:bill][:status])
    redirect_to bills_path
  end

  private

  def bill_params
    params.permit(:bill_type, :amount, :employee_id)
  end

  def fetch_user
    @current_user = current_user
  end

  def validate_employee
    redirect_to root_path unless current_user.is_employee?
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :validate_admin_user
  before_action :fetch_employee, only: [:show, :update, :destroy]
  before_action :fetch_departments, only: [:new, :show]

  def index
    @employees = Employee.all
  end

  def new
  end

  def create
    @employee = Employee.create(employee_params)

    if @employee.save
      redirect_to employees_path
    else
      flash.now[:danger] = 'Invalid email/password'
      render 'new'
    end
  end

  def show
  end

  def update
    if @employee.update(employee_params)
      redirect_to employees_path
    else

    end
  end

  def destroy
    @employee.destroy
  end

  private

  def employee_params
    params.permit(:first_name, :last_name, :email, :designation, :department_id)
  end

  def validate_admin_user
    redirect_to bills_path unless current_user.is_admin?
  end

  def fetch_employee
    @employee = Employee.find_by(id: params[:id])
  end

  def fetch_departments
    @departments = Department.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # Renders the login form
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      if @user.is_admin?
        redirect_to employees_path, flash: { success: 'Successfully Logged in!' }
      else
        redirect_to bills_path
      end
    else
      flash.now[:danger] = 'Invalid email/password'
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bills/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Submitted Bills</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <%= stylesheet_link_tag 'employee', media: 'all', 'data-turbolinks-track': true %>
</head>
<body>
  <div class="bill_form" style="display: flex; flex-direction: column; justify-content: center; align-items: center; gap: 30px; margin-top: 30px;">
    <div id="admin_table" style="display: flex; flex-direction: column; gap: 2rem">
      <% unless @current_user.is_employee? %>
        <a href="/employees"><i class="fa-solid fa-arrow-left"></i></a>
      <% end %>

      <div class="totals-container" style="display: flex; flex-direction: row; margin-bottom: 0;">
        <div class="flex-item">Total Submitted: <%= @bills.count %></div>
        <div class="flex-item right">Total Approved: <%= @approved_count %></div>
      </div>

      <% if @bills.present? %>
        <table>
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Amount</th>
                    <th>Date of Submission</th>
                    <% if @current_user.is_admin? %>
                      <th>Submitted By</th>
                      <th>Department</th>
                    <% end %>
                    <th>Status</th>
                </tr>
            </thead>
            <% @bills.each do |bill| %>
              <tbody>
                <tr>
                    <td><%= bill.bill_type %></td>
                    <td><%= bill.amount %></td>
                    <td><%= bill.created_at.strftime('%d-%m-%Y') %></td>
                    <% if @current_user.is_admin? %>
                      <td><%= bill.employee.first_name %> <%= bill.employee.last_name %></td>
                      <td><%= bill.employee.department.name %></td>
                    <% end %>
                    
                    <td>
                      <% if @current_user.is_admin? %>
                        <%= form_with(model: bill, local: true, html: { class: 'bill-status' }) do |form| %>
                          <%= form.select :status, options_for_select([['Pending', 'pending'], ['Approved', 'approved'], ['Rejected', 'rejected']], selected: bill.status), {}, class: "form-select" %>
                      
                          <%= form.submit "Save", class: "btn btn-primary" %>
                        <% end %>
                      <% else %>
                        <%= bill.status.capitalize %>
                      <% end %>
                    </td>
                </tr>
              </tbody>
            <% end %>
        </table>
      <% end %>


      <% if @current_user.is_employee? %>
        <div class="button-container" style="text-align: center; margin: auto; width: 100%">
          <a href="<%= new_bill_path %>"><button class="btn"><i class="fas fa-plus"></i> Create New Bill</button></a>
        </div>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/bills/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reimbursement Form</title>
    <%= stylesheet_link_tag 'reimbursement', media: 'all', 'data-turbolinks-track': true %>
</head>
<body>

  <div class="form-container">
    <h1>Reimbursement Form</h1>

    <%= form_with url: bills_path, local: true, html: { class: "reimbursement-form" } do |form| %>
      <form>
        <%= form.hidden_field :employee_id, value: current_user.id %>

        <div class="reimbursement_form form-group">
          <label for="type">Type</label>
          <%= form.select :bill_type, options_for_select([['Food', 'food'], ['Travel', 'travel'], ['Office Supplies', 'office-supplies'], ['Education', 'education'], ['Miscellaneous', 'miscellaneous']]), {}, class: "form-select custom-select" %>
        </div>

        <div class="form-group">
          <label for="amount">Amount</label>
          <div class="currency-wrapper">
            <%= form.text_field :amount, placeholder: "Amount", class: "currency", required: true %>
          </div>
        </div>

        <div style="">
          <button type="submit" class="submit-btn">Submit</button>
        </div>
      </form>
    <% end %>
  </div>

</body>
</html>

app/views/employees/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Information</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <%= stylesheet_link_tag 'employee', media: 'all', 'data-turbolinks-track': true %>
  </head>
  <body>
    <div class="button-container" style="display: flex; flex-direction: row; width: 60%; margin: auto; padding: 20px 0px;">
      <div class="flex-item"><h3> Employee List </h3></div>
      <div class="flex-item right"><a href="<%= new_employee_path %>"><button class="btn"><i class="fas fa-plus"></i> Create New Employee</button></a></div>
    </div>

    <table id="admin_table">
      <thead>
        <tr>
          <th>Full Name</th>
          <th>Designation</th>
          <th>Department</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @employees.each do |employee| %>
          <tr>
            <td><%= employee.first_name %> <%= employee.last_name %></td>
            <td><%= employee.designation %></td>
            <td><%= employee.department.name %></td>
            <td>
              <a href="<%= employee_path(employee) %>" class="edit-icon" title="Edit">
                <i class="fas fa-edit"></i>
              </a>
              <a href="<%= employee_path(employee) %>" data-method="delete" class="delete-icon" title="Delete" data-confirm="Are you sure?">
                <i class="fas fa-trash"></i>
              </a>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div style="text-align: center; padding-top: 50px;">
      <p> <a href='/bills'>Click here</a> to view the bills</p>
    </div>
  </body>
</html>

app/views/employees/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Employee Form</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <%= stylesheet_link_tag 'employee', media: 'all', 'data-turbolinks-track': true %>
</head>
<body>
  <div class="create_employee" style="width: 100%; margin: auto;">

    <%= form_with url: employees_path, local: true, html: { class: 'employee-form' } do |form| %>
      <div style="display: flex; flex-direction: row; gap: 20px;">
        <a href="/employees" style="margin: auto 0;"><i class="fa-solid fa-arrow-left"></i></a>
        <h2 style="margin: 0;">Create Employee</h2>
      </div>
      <div class="form-container">
        <div class="third-width">
          <%= form.label :first_name, "First name" %>
          <%= form.text_field :first_name, pattern: '[A-Za-z\s\']+', placeholder: "First name", required: true %>
        </div>
        
        <div class="third-width">
          <%= form.label :last_name, "Last name" %>
          <%= form.text_field :last_name, pattern: '[A-Za-z\s\']+', placeholder: "Last name" %>
        </div>
        
        <div class="third-width">
          <%= form.label :email, "Email Address" %>
          <%= form.email_field :email, placeholder: "Email Address", required: true %>
        </div>
        
        <div class="half-width">
          <%= form.label :designation, "Designation" %>
          <%= form.text_field :designation, placeholder: "Designation", required: true %>
        </div>
        
        <div class="third-width">
          <%= form.label :department, "Department" %>
          <%= form.select :department_id, options_from_collection_for_select(@departments, :id, :name), prompt: 'Choose...', required: true %>
        </div>
      </div>
        
      <div style="align-self: end;">
        <%= form.submit 'Create', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</body>
</html>

app/views/employees/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Form</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <%= stylesheet_link_tag 'employee', media: 'all', 'data-turbolinks-track': true %>
  </head>
  <body>

    <div class="create_employee" style="width: 100%; margin: auto;">
      <%= form_with model: @employee, local: true, html: { class: 'employee-form' } do |form| %>
        <div style="display: flex; flex-direction: row; gap: 20px;">
          <a href="/employees" style="margin: auto 0;"><i class="fa-solid fa-arrow-left"></i></a>
          <h2 style="margin: 0;">Update Employee</h2>
        </div>
        <div class="form-container">
          <div class="third-width">
            <%= form.label :first_name, "First name" %>
            <%= form.text_field :first_name, placeholder: "First name", required: true %>
          </div>
          
          <div class="third-width">
            <%= form.label :last_name, "Last name" %>
            <%= form.text_field :last_name, placeholder: "Last name" %>
          </div>
          
          <div class="third-width">
            <%= form.label :email, "Email Address" %>
            <%= form.email_field :email, placeholder: "Email Address", required: true %>
          </div>
          
          <div class="half-width">
            <%= form.label :designation, "Designation" %>
            <%= form.text_field :designation, placeholder: "Designation", required: true %>
          </div>
          
          <div class="third-width">
            <%= form.label :department, "Department" %>
            <%= form.select :department_id, options_for_select(@departments.map{|x| [x.name, x.id]}, @employee.department_id), { prompt: 'Choose...' } %>
          </div>
          
        </div>
        <div style="align-self: end;">
          <%= form.submit 'Update', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeReimbursement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>